exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "data/",
    "dist",
    "docs/",
    "notebooks/",
    "services/",
    "site-packages",
    "tests/",
    "venv",
]
indent-width = 4
line-length = 120
target-version = "py311"

[lint]
select = [
    # flake8-bugbear
    "B",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # isort
    "I",
    # flake8-simplify
    "SIM",
    # pyupgrade
    "UP",
]
ignore = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

fixable = ["ALL"]
unfixable = []

[format]
exclude = ["*.ipynb"]

docstring-code-format = true
docstring-code-line-length = "dynamic" 

indent-style = "space"
line-ending = "auto"
quote-style = "double"

skip-magic-trailing-comma = false
